// @generated by `cargo test --manifest-path src-tauri/Cargo.toml`
// Do not edit by hand.

export type UciOption = { name: string, optionType: string, defaultValue: string | null, value: string | null, min: number | null, max: number | null, choices: Array<string>, };

export type OpeningBookConfig = { enabled: boolean, path: string, name: string, format: string, maxPlies: number, topMovePercent: number, entryCount: number, };

export type EngineProfile = { id: string, name: string, path: string, author: string | null, optionCount: number, lastProbedAtMs?: number, probeOk?: boolean, options: Array<UciOption>, openingBook: OpeningBookConfig | null, };

export type EngineOptionUpdate = { name: string, value: string | null, };

export type OpeningBookUpdate = { engineId: string, path: string, enabled: boolean, maxPlies: number, topMovePercent: number, };

export type AccountProfile = { id: string, username: string, engineId: string, rating: number | null,
/**
 * Desired supervisor state. Headless runners restore enabled accounts
 * after a service restart; transient runtime status remains separate.
 */
enabled: boolean, };

export type BotRuntime = { accountId: string, status: string, error: string | null, };

export type EngineTelemetry = { depth?: number, selectiveDepth?: number, scoreCp?: number, mateIn?: number, scoreBound?: string, nodes?: number, nodesPerSecond?: number, timeMs?: number, hashFull?: number, tablebaseHits?: number, multiPv?: number, principalVariation: Array<string>, raw: string, };

export type LiveGame = { id: string, accountId: string, botUsername: string, opponent: string, botRating: number | null, opponentRating: number | null, color: string, initialFen: string, moves: string, status: string, whiteTime: number, blackTime: number, whiteIncrement: number, blackIncrement: number, clockUpdatedAt: number, result: string | null, engineLine: string | null, engineInfo: EngineTelemetry | null, engineThinking: boolean, error: string | null, };

export type CampaignEvent = { id: string, timestamp: number, kind: string, title: string, detail: string | null, };

export type CampaignSettings = { accountId: string, minRating: number, maxRating: number, concurrency: number, clockLimit: number, clockIncrement: number,
/**
 * Defaults to rated matchmaking when absent from persisted backend data.
 */
rated: boolean, color: string,
/**
 * Accept compatible incoming challenges while this campaign is active.
 */
acceptIncomingChallenges: boolean,
/**
 * Mutually exclusive automatic stop conditions. `None` means the run is
 * stopped manually.
 */
stopAfterMinutes: number | null,
/**
 * Count only terminal, non-aborted games toward the campaign limit.
 */
stopAfterGames: number | null, };

export type CampaignStatus = "starting" | "discovering" | "challenging" | "running" | "waiting" | "backoff" | "stopping" | "stopped" | "error" | "unknown";

export type CampaignRuntime = { accountId: string, status: CampaignStatus, activeGames: number, pendingChallenges: number, eligibleBots: number, onlineBotsScanned: number, challengesSent: number, gamesStarted: number,
/**
 * Terminal games in this campaign whose Lichess result is not aborted or
 * no-start. This is the authoritative counter for a game-limited run.
 */
gamesCompleted: number, lastOpponent: string | null, activity: string, error: string | null, nextScanAt: number | null, stopAt: number | null, events: Array<CampaignEvent>, };

export type AppSnapshot = { engines: Array<EngineProfile>, accounts: Array<AccountProfile>, runtimes: Array<BotRuntime>, games: Array<LiveGame>, campaigns: Array<CampaignSettings>, campaignRuntimes: Array<CampaignRuntime>, };

export type AddAccountRequest = { token: string, engineId: string, };

export type AddAccountResult = { account: AccountProfile,
/**
 * OAuth scopes reported by Lichess for the token that was just validated.
 */
scopes: Array<string>,
/**
 * Required matchmaking scopes absent from `scopes`, in stable display order.
 */
missingForMatchmaking: Array<string>,
/**
 * Explicitly distinguishes a token that cannot operate bot games at all.
 */
canPlayGames: boolean, };

export type ChallengeRequest = { accountId: string, opponent: string, clockLimit: number, clockIncrement: number, rated: boolean, color: string, variant: string, };

export type ChallengeResult = { id: string, status: string, url: string, };

export type ImportReport = { imported: number, skipped: number, scanned: number, };

export type ScorebookFilter = { accountId: string | null, engineId: string | null, perf: string | null,
/**
 * Inclusive epoch-ms window on finished_at_ms. Applies to every
 * aggregation except `activity`, which is the brush overview and always
 * covers the full span of the account/engine/perf-filtered history.
 */
fromMs: number | null, toMs: number | null, };

export type Streak = {
/**
 * "win" | "draw" | "loss" | "none"
 */
kind: string, length: number, };

export type EngineLine = { engineId: string | null, engineName: string, games: number, wins: number, draws: number, losses: number, scorePercent: number, avgOpponentRating: number | null, performanceRating: number | null, };

export type ColorLine = { color: string, games: number, wins: number, draws: number, losses: number, scorePercent: number, };

export type PerfLine = { perf: string, games: number, wins: number, draws: number, losses: number, scorePercent: number, };

export type BandLine = {
/**
 * e.g. "1800–1999"
 */
label: string, minRating: number, games: number, wins: number, draws: number, losses: number, scorePercent: number, };

export type TerminationLine = { status: string, games: number, wins: number, draws: number, losses: number, };

export type OpponentLine = { name: string, games: number, wins: number, draws: number, losses: number, scorePercent: number, lastPlayedAtMs: number, };

export type DayLine = { dayStartMs: number, games: number, scorePoints: number, };

export type RatingPoint = { atMs: number, rating: number, };

export type OpeningLine = { name: string, games: number, scorePercent: number, };

export type AccountRef = { id: string, username: string, };

export type EngineRef = { id: string, name: string, };

export type LabGame = { id: string, opponent: string, opponentRating: number | null, finishedAtMs: number, peakEvalCp: number, result: string, engineName: string | null, };

export type EngineLabLine = { engineId: string | null, engineName: string, games: number, avgDepth: number | null, avgBlunders: number, conversionRate: number | null, avgMoveTimeMs: number | null, };

export type DepthLine = { perf: string, games: number, avgDepth: number | null, minDepth: number | null, };

export type BookLab = { gamesWithBook: number, gamesWithout: number, scoreWith: number, scoreWithout: number | null, avgBookPlies: number | null,
/**
 * Mean of the eval snapshot taken right after the last book move
 * (eval_series_cp[book_plies]), over with-book games where it exists.
 */
avgExitEvalCp: number | null, };

export type ReliabilityTotals = { engineRestarts: number, submissionRetries: number, streamReconnects: number,
/**
 * Defaults across desktop/runner version skew where the older peer did
 * not yet report this additive reliability counter.
 */
flagSafetyStops: number, failureResigns: number, };

export type ConfigLine = { fingerprint: string, engineName: string, games: number, scorePercent: number, firstSeenMs: number, lastSeenMs: number, };

export type ScorebookLab = { telemetryGames: number,
/**
 * max_eval_cp >= 300 but the game did not end in a win; most recent first.
 */
thrownWins: Array<LabGame>,
/**
 * min_eval_cp <= -300 but the game did not end in a loss; most recent first.
 */
steals: Array<LabGame>,
/**
 * Among games with max_eval_cp >= 300: percent ending "win".
 */
conversionRate: number | null,
/**
 * Among games with min_eval_cp <= -300: percent ending "win" or "draw".
 */
defenseRate: number | null, avgBlundersPerGame: number | null, byEngineLab: Array<EngineLabLine>, depthByPerf: Array<DepthLine>,
/**
 * Losses by outoftime/timeout whose final eval snapshot was >= 150.
 */
flaggedWinning: number, avgEndClockMs: number | null, book: BookLab | null, reliability: ReliabilityTotals, byConfig: Array<ConfigLine>, };

export type ScorebookStats = { totalGames: number, wins: number, draws: number, losses: number, scorePercent: number, streak: Streak, avgOpponentRating: number | null, performanceRating: number | null, byEngine: Array<EngineLine>, byColor: Array<ColorLine>, byPerf: Array<PerfLine>, byOpponentBand: Array<BandLine>, byTermination: Array<TerminationLine>, timeLosses: number, topOpponents: Array<OpponentLine>,
/**
 * Full-span brush overview; unaffected by the from_ms/to_ms window.
 */
activity: Array<DayLine>,
/**
 * "day" | "week" | "month" — the bucket size activity was computed with.
 */
activityBucket: string, ratingSeries: Array<RatingPoint>, openings: Array<OpeningLine>, accounts: Array<AccountRef>, engines: Array<EngineRef>, imported: number, recorded: number,
/**
 * None when the filtered set has no telemetry games.
 */
lab: ScorebookLab | null, };

export type LogRetention = { captureEnabled: boolean, maxTotalMb: number, maxAgeDays: number, };

export type LogSessionSummary = { id: string, kind: string, gameId: string | null, accountId: string, botUsername: string, opponent: string | null, engineId: string, engineName: string, color: string | null, clock: string | null, startedAtMs: number, finishedAtMs: number | null, status: string | null, result: string | null, lineCount: number, searchCount: number, compressedBytes: number, rawBytes: number, droppedLines: number, live: boolean, };

export type LogFilter = { accountId: string | null, engineId: string | null, fromMs: number | null, toMs: number | null,
/**
 * Case-insensitive substring over opponent, game id, engine name and bot
 * username.
 */
query: string | null, limit: number | null, };

export type LogQuery = { text: string, regex: boolean, caseSensitive: boolean, limit: number, };

export type LogLine = { index: number, atMs: number, direction: string, text: string, };

export type LogHeaderField = { key: string, value: string, };

export type LogPage = { sessionId: string, totalLines: number, offset: number, lines: Array<LogLine>, header: Array<LogHeaderField>, live: boolean, };

export type LogSearchBlock = { moveNumber: number, ply: number, color: string, startLine: number, endLine: number, bestMove: string | null, elapsedMs: number | null, depth: number | null, scoreCp: number | null, mateIn: number | null, };

export type LogMatch = { lineIndex: number, direction: string, text: string, };

export type LogSessionMatches = { session: LogSessionSummary, matchCount: number, first: LogMatch | null, };

export type LogsOverview = { sessionCount: number, compressedBytes: number, rawBytes: number, oldestStartedAtMs: number | null, liveCount: number, retention: LogRetention, };

export type ExportMode = "annotated" | "plain" | "archive";

export type DiagnosticEntry = { id: string, atMs: number, level: string, source: string,
/**
 * The Lichess account the event concerns, when it concerns one.
 */
accountId: string | null, gameId: string | null,
/**
 * One line, already phrased for an operator.
 */
message: string,
/**
 * The underlying error text, stack of causes, or offending payload.
 */
detail: string | null, };

export type DiagnosticFilter = {
/**
 * MINIMUM level: "info" shows everything, "warn" hides info, "error"
 * shows only errors.
 */
level: string | null, source: string | null, accountId: string | null,
/**
 * Case-insensitive substring over message and detail.
 */
query: string | null,
/**
 * 0 or absent means "everything in memory".
 */
limit: number | null, };

export type EngineRoot = {
/**
 * Stable administrator-chosen identifier. The absolute host path never
 * crosses the runner protocol.
 */
id: string, label: string, };

export type OpeningBookAsset = {
/**
 * Canonical runner-local path. Only entries from the administrator's
 * opening-book allowlist are exposed here.
 */
path: string, name: string, size: number, };

export type EngineBrowseEntryKind = "directory" | "file";

export type EngineBrowseEntry = { name: string, relativePath: string, kind: EngineBrowseEntryKind, size: number, modifiedAtMs: number | null, executable: boolean, };

export type EngineBrowseRequest = { rootId: string,
/**
 * Slash-separated path relative to the configured root. Empty means the
 * root itself; absolute paths and empty interior components are invalid.
 */
relativePath: string, cursor: string | null, pageEntries: number | null, };

export type EngineBrowseResponse = { rootId: string, relativePath: string, entries: Array<EngineBrowseEntry>, nextCursor: string | null, };

export type RunnerSettingsView = { mode: string, url: string | null, paired: boolean, activeMode: string, source: string, restartRequired: boolean, allowInsecureRemoteHttp: boolean, };

export type RunnerConnectionTest = { hostname: string, operatingSystem: string, architecture: string, logicalCpus: number, };

export type RunnerConnectionState = "embedded" | "connected" | "reconnecting" | "disconnected";

export type RunnerConnectionEvent = { backendGeneration: number, state: RunnerConnectionState, attempt: number, lastOkTs: number | null, detail: string | null, };

export type BackendSnapshotEvent = { backendGeneration: number, payload: AppSnapshot, };

export type BackendNotificationEvent = { backendGeneration: number, payload: null, };
